
spring.application.name=float


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.url=jdbc:mysql://localhost:3306/db_api_sec
spring.datasource.username=
spring.datasource.password=